/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;
import model.Produto;

/**
 *
 * @author pedro
 */
public class EstoqueView extends javax.swing.JFrame {

    Funcionario funcionarioLogado = LoginView.funcionarioLogado;

    /**
     *
     * Creates new form ProdutosView
     */
    public EstoqueView() {
        initComponents();
        preencheTabelaProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtUserLogado = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPesquisarProduto = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        txtPreco = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMediaGastoPorServico = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        logoPrincipalPequena = new javax.swing.JLabel();
        traco = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFinancas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btnEstoque = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1375, 700));

        painel.setBackground(new java.awt.Color(204, 204, 204));
        painel.setPreferredSize(new java.awt.Dimension(820, 600));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 246, 50, 30));

        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQuantidade.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtQuantidadeCaretUpdate(evt);
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        painel.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 343, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pesquisar");
        painel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userLogado.png"))); // NOI18N
        painel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, -1));

        btnEditar.setBackground(new java.awt.Color(26, 113, 228));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Salvar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        painel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 100, 30));

        txtUserLogado.setBackground(new java.awt.Color(204, 204, 204));
        txtUserLogado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtUserLogado.setForeground(new java.awt.Color(102, 102, 102));
        txtUserLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUserLogado.setToolTipText("");
        painel.add(txtUserLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 269, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Produto");
        painel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Quantidade");
        painel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtPesquisarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisarProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarProdutoCaretUpdate(evt);
            }
        });
        txtPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarProdutoActionPerformed(evt);
            }
        });
        painel.add(txtPesquisarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 246, 343, 25));

        txtProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProdutoCaretUpdate(evt);
            }
        });
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        painel.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 343, 25));

        tblProdutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Produto", "Quantidade", "Preço"
            }
        ));
        tblProdutos.setPreferredSize(new java.awt.Dimension(730, 400));
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setMinWidth(40);
            tblProdutos.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProdutos.getColumnModel().getColumn(3).setMinWidth(200);
            tblProdutos.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        painel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 1110, 460));

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPreco.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPrecoCaretUpdate(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        painel.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 343, 25));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Minimo em estoque");
        painel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Máximo em estoque");
        painel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        txtMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMinCaretUpdate(evt);
            }
        });
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });
        painel.add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 60, 25));

        txtMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMax.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMax.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMaxCaretUpdate(evt);
            }
        });
        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });
        painel.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 60, 25));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Média gasto por serviço");
        painel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        txtMediaGastoPorServico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMediaGastoPorServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMediaGastoPorServico.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMediaGastoPorServicoCaretUpdate(evt);
            }
        });
        txtMediaGastoPorServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMediaGastoPorServicoActionPerformed(evt);
            }
        });
        painel.add(txtMediaGastoPorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 60, 25));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Preço");
        painel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        menuBar.setBackground(new java.awt.Color(0, 102, 102));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(250, 600));
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarMouseClicked(evt);
            }
        });

        logoPrincipalPequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequena.png"))); // NOI18N

        traco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/traco.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setAutoscrolls(true);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setPreferredSize(new java.awt.Dimension(250, 70));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnInicio.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 103);
        btnInicio.add(jLabel8, gridBagConstraints);

        btnAgenda.setBackground(new java.awt.Color(0, 102, 102));
        btnAgenda.setAutoscrolls(true);
        btnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda.setPreferredSize(new java.awt.Dimension(250, 70));
        btnAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendaMouseExited(evt);
            }
        });
        btnAgenda.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnAgenda.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 83);
        btnAgenda.add(jLabel10, gridBagConstraints);

        btnClientes.setBackground(new java.awt.Color(0, 102, 102));
        btnClientes.setAutoscrolls(true);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setPreferredSize(new java.awt.Dimension(250, 70));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.setLayout(new java.awt.GridBagLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnClientes.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 84);
        btnClientes.add(jLabel12, gridBagConstraints);

        btnFinancas.setBackground(new java.awt.Color(0, 102, 102));
        btnFinancas.setAutoscrolls(true);
        btnFinancas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinancas.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFinancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinancasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinancasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinancasMouseExited(evt);
            }
        });
        btnFinancas.setLayout(new java.awt.GridBagLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 54, 11, 0);
        btnFinancas.add(jLabel15, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("Finanças");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 78);
        btnFinancas.add(btn6, gridBagConstraints);

        btnEstoque.setBackground(new java.awt.Color(37, 142, 142));
        btnEstoque.setAutoscrolls(true);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setPreferredSize(new java.awt.Dimension(250, 70));
        btnEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseExited(evt);
            }
        });
        btnEstoque.setLayout(new java.awt.GridBagLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnEstoque.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 81);
        btnEstoque.add(jLabel14, gridBagConstraints);

        btnFuncionarios.setBackground(new java.awt.Color(0, 102, 102));
        btnFuncionarios.setAutoscrolls(true);
        btnFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });
        btnFuncionarios.setLayout(new java.awt.GridBagLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnFuncionarios.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Funcionários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 45);
        btnFuncionarios.add(jLabel17, gridBagConstraints);

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setAutoscrolls(true);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setPreferredSize(new java.awt.Dimension(250, 70));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new java.awt.GridBagLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnLogout.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 88);
        btnLogout.add(jLabel19, gridBagConstraints);

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traco)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoPrincipalPequena))))
            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(traco, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoPrincipalPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        preencheTabelaProduto();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtQuantidadeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtQuantidadeCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeCaretUpdate

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(26, 0, 240));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(26, 113, 228));
    }//GEN-LAST:event_btnEditarMouseExited

    private void txtPesquisarProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoCaretUpdate
        // TODO add your handling code here:
        preencheTabelaProduto();
    }//GEN-LAST:event_txtPesquisarProdutoCaretUpdate

    private void txtPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarProdutoActionPerformed

    private void txtProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProdutoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoCaretUpdate

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
        RetornaLinhaTabela();
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        btnInicio.setBackground(new Color(37, 142, 142));

        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        btnInicio.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseEntered
        // TODO add your handling code here:
        btnAgenda.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendaMouseEntered

    private void btnAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseExited
        // TODO add your handling code here:
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnAgendaMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnFinancasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseEntered
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFinancasMouseEntered

    private void btnFinancasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseExited
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFinancasMouseExited

    private void btnEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseEntered
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnEstoqueMouseEntered

    private void btnEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseExited
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnEstoqueMouseExited

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(37, 142, 142));

        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        dispose();
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(37, 142, 142));

        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void menuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseClicked
        // TODO add your handling code here:
        AgendaView agendaView = new AgendaView();
        agendaView.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuBarMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        ClientesView clientesView = new ClientesView();
        clientesView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void txtPrecoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPrecoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCaretUpdate

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtMinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMinCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinCaretUpdate

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void txtMaxCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMaxCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxCaretUpdate

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void btnAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseClicked
        // TODO add your handling code here:
        AgendaView agendaView = new AgendaView();
        agendaView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgendaMouseClicked

    private void btnFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseClicked
        // TODO add your handling code here:
        if (this.funcionarioLogado.isAcesso()) {
            FuncionarioView funcionarioView = new FuncionarioView();
            funcionarioView.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão");
        }
    }//GEN-LAST:event_btnFuncionariosMouseClicked

    private void txtMediaGastoPorServicoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMediaGastoPorServicoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMediaGastoPorServicoCaretUpdate

    private void txtMediaGastoPorServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMediaGastoPorServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMediaGastoPorServicoActionPerformed

    private void btnFinancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseClicked
        // TODO add your handling code here:
        FinancasView financasView = new FinancasView();
        financasView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFinancasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn6;
    private javax.swing.JPanel btnAgenda;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEstoque;
    private javax.swing.JPanel btnFinancas;
    private javax.swing.JPanel btnFuncionarios;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoPrincipalPequena;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel painel;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JLabel traco;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMediaGastoPorServico;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JLabel txtUserLogado;
    // End of variables declaration//GEN-END:variables

    public void preencheTabelaProduto() {

        ProdutoDAO produtoDAO = new ProdutoDAO();
        String pesquisa = txtPesquisarProduto.getText().toUpperCase();

        List<Produto> listaProdutos = produtoDAO.getProdutos(pesquisa);

        DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
        tabelaProdutos.setRowCount(0);

        for (Produto p : listaProdutos) {

            DecimalFormat formato = new DecimalFormat("R$ #,##0.00");
            String valorFormatado = (formato.format(p.getPrecoUnidade()));

            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.US);
            symbols.setDecimalSeparator('.');
            DecimalFormat quant = new DecimalFormat("#.#", symbols);
            String quantidadeFormatada = quant.format(p.getQuantidade());

            Object[] obj = new Object[]{
                p.getId(),
                p.getNome(),
                quantidadeFormatada,
                valorFormatado
            };
            tabelaProdutos.addRow(obj);
        }

        txtUserLogado.setText(funcionarioLogado.getNome());
    }

    public void RetornaLinhaTabela() {
        DefaultTableModel tblModel = (DefaultTableModel) tblProdutos.getModel();
        int i = tblProdutos.getSelectedRow();
        String id = tblModel.getValueAt(i, 0).toString();

        int idPesquisa = Integer.parseInt(id);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        Produto produto = produtoDAO.getProduto(idPesquisa);

        txtProduto.setText(produto.getNome());
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.US);
        symbols.setDecimalSeparator('.');
        DecimalFormat quant = new DecimalFormat("#.#", symbols);
        txtQuantidade.setText(quant.format(produto.getQuantidade()));
        DecimalFormat moeda = new DecimalFormat("R$ #,##0.00");
        txtPreco.setText(moeda.format(produto.getPrecoUnidade()));
        txtMin.setText(String.valueOf(produto.getMin()));
        txtMax.setText(String.valueOf(produto.getMax()));
        txtMediaGastoPorServico.setText(String.valueOf(produto.getMediaGasto()));
    }

    public void remover() {
        DefaultTableModel tblModel = (DefaultTableModel) tblProdutos.getModel();
        int i = tblProdutos.getSelectedRow();
        String id = tblModel.getValueAt(i, 0).toString();

        int idPesquisa = Integer.parseInt(id);
        int op = JOptionPane.showConfirmDialog(null, ("Deseja remover o produto selecionado de id " + idPesquisa));
        if (op == 0) {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            produtoDAO.remover(idPesquisa);
            preencheTabelaProduto();
            limpaCampos();
        }
    }

    public void editar() {
        DefaultTableModel tblModel = (DefaultTableModel) tblProdutos.getModel();
        int i = tblProdutos.getSelectedRow();
        String idString = tblModel.getValueAt(i, 0).toString();

        if (!idString.equals("")) {
            int id = Integer.parseInt(idString);

            int op = JOptionPane.showConfirmDialog(null, ("Deseja editar o produto de id = " + id + " ?"));

            if (op == 0) {
                String nome = txtProduto.getText().toUpperCase();
                Double quantidade = Double.parseDouble(txtQuantidade.getText());
                Double max = Double.parseDouble(txtMax.getText());
                Double min = Double.parseDouble(txtMin.getText());
                Double mediaGasto = Double.parseDouble(txtMediaGastoPorServico.getText());

                String precoFormatado = txtPreco.getText();
                if (precoFormatado.substring(0, 2).equals("R$")) {
                    precoFormatado = precoFormatado.substring(2).trim();
                }
                double preco = convertarPrecoFormatadoParaDouble(precoFormatado);

                Produto produto = new Produto();
                produto.setId(id);
                produto.setNome(nome);
                produto.setPrecoUnidade(preco);
                produto.setQuantidade(quantidade);
                produto.setMin(min);
                produto.setMax(max);
                produto.setMediaGasto(mediaGasto);

                ProdutoDAO produtoDAO = new ProdutoDAO();
                produtoDAO.editar(produto);
                limpaCampos();
                preencheTabelaProduto();
            }
        }
    }

    public void limpaCampos() {
        txtProduto.setText("");
        txtPesquisarProduto.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        txtMax.setText("");
        txtMin.setText("");
        txtMediaGastoPorServico.setText("");
    }

    public double convertarPrecoFormatadoParaDouble(String valorFormatado) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
        char decimalSeparator = symbols.getDecimalSeparator();

        // Removendo o separador de milhar, caso exista
        valorFormatado = valorFormatado.replace(Character.toString(symbols.getGroupingSeparator()), "");

        // Substituindo a vírgula pelo ponto
        valorFormatado = valorFormatado.replace(Character.toString(decimalSeparator), ".");

        double valorDouble = Double.parseDouble(valorFormatado);
        return valorDouble;
    }

    public void subtrairProduto(String produtoSelecionado) {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        if (produtoSelecionado.equals("SHAMPOO")) {
            Produto produto = produtoDAO.getProduto(1);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("CERA")) {
            Produto produto = produtoDAO.getProduto(2);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("LIMPA-BAU")) {
            Produto produto = produtoDAO.getProduto(3);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("DESENGRAXANTE")) {
            Produto produto = produtoDAO.getProduto(4);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("REVITALIZADOR-DE-PLASTICOS")) {
            Produto produto = produtoDAO.getProduto(5);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("AROMATIZANTE")) {
            Produto produto = produtoDAO.getProduto(6);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("MASSA-DE-POLIR")) {
            Produto produto = produtoDAO.getProduto(7);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("MASSA-DE-POLIR-FAROIS")) {
            Produto produto = produtoDAO.getProduto(7);
            double novaQuantidade = produto.getQuantidade() - 0.1;
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("PRETINHO")) {
            Produto produto = produtoDAO.getProduto(8);
            double novaQuantidade = produto.getQuantidade() - produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }
    }

    public void somarProduto(String produtoSelecionado) {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        if (produtoSelecionado.equals("SHAMPOO")) {
            Produto produto = produtoDAO.getProduto(1);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("CERA")) {
            Produto produto = produtoDAO.getProduto(2);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("LIMPA-BAU")) {
            Produto produto = produtoDAO.getProduto(3);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("DESENGRAXANTE")) {
            Produto produto = produtoDAO.getProduto(4);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("REVITALIZADOR-DE-PLASTICOS")) {
            Produto produto = produtoDAO.getProduto(5);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("AROMATIZANTE")) {
            Produto produto = produtoDAO.getProduto(6);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("MASSA-DE-POLIR")) {
            Produto produto = produtoDAO.getProduto(7);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("MASSA-DE-POLIR-FAROIS")) {
            Produto produto = produtoDAO.getProduto(7);
            double novaQuantidade = produto.getQuantidade() + 0.1;
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }

        if (produtoSelecionado.equals("PRETINHO")) {
            Produto produto = produtoDAO.getProduto(8);
            double novaQuantidade = produto.getQuantidade() + produto.getMediaGasto();
            produtoDAO.subtrairProduto(produto.getId(), novaQuantidade);
        }
    }

    public double somarDispesa(String produtoSelecionado) {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        if (produtoSelecionado.equals("SHAMPOO")) {
            Produto produto = produtoDAO.getProduto(1);
            System.out.println(produto.getPrecoUnidade() * produto.getMediaGasto());
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("CERA")) {
            Produto produto = produtoDAO.getProduto(2);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("LIMPA-BAU")) {
            Produto produto = produtoDAO.getProduto(3);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("DESENGRAXANTE")) {
            Produto produto = produtoDAO.getProduto(4);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("REVITALIZADOR-DE-PLASTICOS")) {
            Produto produto = produtoDAO.getProduto(5);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("AROMATIZANTE")) {
            Produto produto = produtoDAO.getProduto(6);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("MASSA-DE-POLIR")) {
            Produto produto = produtoDAO.getProduto(7);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("MASSA-DE-POLIR-FAROIS")) {
            Produto produto = produtoDAO.getProduto(7);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else if (produtoSelecionado.equals("PRETINHO")) {
            Produto produto = produtoDAO.getProduto(8);
            return produto.getPrecoUnidade() * produto.getMediaGasto();
        }else{
            return 0.0;
        }
    }

}
