/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendamentoDAO;
import dao.DispesaDAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import model.Agendamento;
import model.Dispesa;
import static view.LoginView.funcionarioLogado;

/**
 *
 * @author Pedro
 */
public class FinancasView extends javax.swing.JFrame {

    /**
     * Creates new form FinancasView
     */
    public FinancasView() {
        initComponents();
        preencheTabela();
        calcularTudo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuBar = new javax.swing.JPanel();
        logoPrincipalPequena = new javax.swing.JLabel();
        traco = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFinancas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btnEstoque = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinancas = new javax.swing.JTable();
        btnAgendamento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLucroBruto = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTotalDispesas = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtLucroLiquido = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserLogado = new javax.swing.JLabel();
        txtDispesasFuncionarios = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtDispesasProdutos = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtDispesasFixas = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1375, 700));

        menuBar.setBackground(new java.awt.Color(0, 102, 102));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(250, 600));
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarMouseClicked(evt);
            }
        });

        logoPrincipalPequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequena.png"))); // NOI18N

        traco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/traco.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setAutoscrolls(true);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setPreferredSize(new java.awt.Dimension(250, 70));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnInicio.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 103);
        btnInicio.add(jLabel8, gridBagConstraints);

        btnAgenda.setBackground(new java.awt.Color(0, 102, 102));
        btnAgenda.setAutoscrolls(true);
        btnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda.setPreferredSize(new java.awt.Dimension(250, 70));
        btnAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendaMouseExited(evt);
            }
        });
        btnAgenda.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnAgenda.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 83);
        btnAgenda.add(jLabel10, gridBagConstraints);

        btnClientes.setBackground(new java.awt.Color(0, 102, 102));
        btnClientes.setAutoscrolls(true);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setPreferredSize(new java.awt.Dimension(250, 70));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.setLayout(new java.awt.GridBagLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnClientes.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 84);
        btnClientes.add(jLabel12, gridBagConstraints);

        btnFinancas.setBackground(new java.awt.Color(37, 142, 142));
        btnFinancas.setAutoscrolls(true);
        btnFinancas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinancas.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFinancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinancasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinancasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinancasMouseExited(evt);
            }
        });
        btnFinancas.setLayout(new java.awt.GridBagLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 54, 11, 0);
        btnFinancas.add(jLabel15, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("Finanças");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 78);
        btnFinancas.add(btn6, gridBagConstraints);

        btnEstoque.setBackground(new java.awt.Color(0, 102, 102));
        btnEstoque.setAutoscrolls(true);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setPreferredSize(new java.awt.Dimension(250, 70));
        btnEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseExited(evt);
            }
        });
        btnEstoque.setLayout(new java.awt.GridBagLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnEstoque.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 81);
        btnEstoque.add(jLabel14, gridBagConstraints);

        btnFuncionarios.setBackground(new java.awt.Color(0, 102, 102));
        btnFuncionarios.setAutoscrolls(true);
        btnFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });
        btnFuncionarios.setLayout(new java.awt.GridBagLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnFuncionarios.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Funcionários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 45);
        btnFuncionarios.add(jLabel17, gridBagConstraints);

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setAutoscrolls(true);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setPreferredSize(new java.awt.Dimension(250, 70));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new java.awt.GridBagLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnLogout.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 88);
        btnLogout.add(jLabel19, gridBagConstraints);

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traco)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoPrincipalPequena))))
            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(traco, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoPrincipalPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painel.setBackground(new java.awt.Color(204, 204, 204));
        painel.setPreferredSize(new java.awt.Dimension(820, 600));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        tblFinancas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFinancas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Dispesa Fixa", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFinancas.setPreferredSize(new java.awt.Dimension(730, 400));
        tblFinancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFinancasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFinancas);
        if (tblFinancas.getColumnModel().getColumnCount() > 0) {
            tblFinancas.getColumnModel().getColumn(0).setMinWidth(40);
            tblFinancas.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        painel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 1110, 410));

        btnAgendamento.setBackground(new java.awt.Color(0, 102, 102));
        btnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adicionar");

        javax.swing.GroupLayout btnAgendamentoLayout = new javax.swing.GroupLayout(btnAgendamento);
        btnAgendamento.setLayout(btnAgendamentoLayout);
        btnAgendamentoLayout.setHorizontalGroup(
            btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgendamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        btnAgendamentoLayout.setVerticalGroup(
            btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgendamentoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        painel.add(btnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, -1, 30));

        btnCancelar.setBackground(new java.awt.Color(200, 59, 34));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remover.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Remover");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap())
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        painel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 100, 30));

        btnEditar.setBackground(new java.awt.Color(26, 113, 228));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Salvar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel29))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        painel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 100, 30));

        att.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        att.setToolTipText("");
        att.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attMouseClicked(evt);
            }
        });
        painel.add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        painel.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 290, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Pesquisar");
        painel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtLucroBruto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLucroBruto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLucroBruto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtLucroBrutoCaretUpdate(evt);
            }
        });
        txtLucroBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLucroBrutoActionPerformed(evt);
            }
        });
        painel.add(txtLucroBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 25));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Lucro Bruto");
        painel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtTotalDispesas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalDispesas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalDispesas.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTotalDispesasCaretUpdate(evt);
            }
        });
        txtTotalDispesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDispesasActionPerformed(evt);
            }
        });
        painel.add(txtTotalDispesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 25));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Total Dispesas");
        painel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtLucroLiquido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLucroLiquido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLucroLiquido.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtLucroLiquidoCaretUpdate(evt);
            }
        });
        txtLucroLiquido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLucroLiquidoActionPerformed(evt);
            }
        });
        painel.add(txtLucroLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 25));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Lucro Liquido");
        painel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userLogado.png"))); // NOI18N
        painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        txtUserLogado.setBackground(new java.awt.Color(204, 204, 204));
        txtUserLogado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtUserLogado.setForeground(new java.awt.Color(102, 102, 102));
        txtUserLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUserLogado.setToolTipText("");
        painel.add(txtUserLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 269, 20));

        txtDispesasFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDispesasFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDispesasFuncionarios.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDispesasFuncionariosCaretUpdate(evt);
            }
        });
        txtDispesasFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDispesasFuncionariosActionPerformed(evt);
            }
        });
        painel.add(txtDispesasFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, 25));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Funcionários");
        painel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        txtDispesasProdutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDispesasProdutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDispesasProdutos.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDispesasProdutosCaretUpdate(evt);
            }
        });
        txtDispesasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDispesasProdutosActionPerformed(evt);
            }
        });
        painel.add(txtDispesasProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 200, 25));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Produtos");
        painel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtDispesasFixas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDispesasFixas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDispesasFixas.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDispesasFixasCaretUpdate(evt);
            }
        });
        txtDispesasFixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDispesasFixasActionPerformed(evt);
            }
        });
        painel.add(txtDispesasFixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 200, 25));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Dispesas Fixas");
        painel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTitulo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTituloCaretUpdate(evt);
            }
        });
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        painel.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 200, 25));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Tabela Dispesas Fixas");
        painel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Titulo");
        painel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPreco.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPrecoCaretUpdate(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        painel.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 200, 25));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Preço");
        painel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        btnInicio.setBackground(new Color(37, 142, 142));

        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));
        btnInicio.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseClicked
        // TODO add your handling code here:
        AgendaView agendaView = new AgendaView();
        agendaView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgendaMouseClicked

    private void btnAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseEntered
        // TODO add your handling code here:
        btnAgenda.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendaMouseEntered

    private void btnAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseExited
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));
        btnAgenda.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendaMouseExited

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        ClientesView clientesView = new ClientesView();
        clientesView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnFinancasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseEntered
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFinancasMouseEntered

    private void btnFinancasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseExited
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFinancasMouseExited

    private void btnEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseClicked
        // TODO add your handling code here:
        EstoqueView estoqueView = new EstoqueView();
        estoqueView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEstoqueMouseClicked

    private void btnEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseEntered
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnEstoqueMouseEntered

    private void btnEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseExited
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnEstoqueMouseExited

    private void btnFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseClicked
        // TODO add your handling code here:
        FuncionarioView funcionarioView = new FuncionarioView();
        funcionarioView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFuncionariosMouseClicked

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(37, 142, 142));

        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        dispose();
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(37, 142, 142));

        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void menuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarMouseClicked

    private void tblFinancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFinancasMouseClicked
        // TODO add your handling code here:
        RetornaLinhaTabela();
    }//GEN-LAST:event_tblFinancasMouseClicked

    private void btnAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseClicked
        // TODO add your handling code here:
        CadastroDispesaView cadastroDispesaView = new CadastroDispesaView();
        cadastroDispesaView.setVisible(true);
    }//GEN-LAST:event_btnAgendamentoMouseClicked

    private void btnAgendamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseEntered
        // TODO add your handling code here:
        btnAgendamento.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnAgendamentoMouseEntered

    private void btnAgendamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseExited
        // TODO add your handling code here:
        btnAgendamento.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendamentoMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(160, 0, 0));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(200, 59, 34));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(26, 0, 240));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(26, 113, 228));
    }//GEN-LAST:event_btnEditarMouseExited

    private void attMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attMouseClicked
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_attMouseClicked

    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtLucroBrutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtLucroBrutoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroBrutoCaretUpdate

    private void txtLucroBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucroBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroBrutoActionPerformed

    private void txtTotalDispesasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTotalDispesasCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDispesasCaretUpdate

    private void txtTotalDispesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDispesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDispesasActionPerformed

    private void txtLucroLiquidoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtLucroLiquidoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroLiquidoCaretUpdate

    private void txtLucroLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucroLiquidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroLiquidoActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        InicioView inicioView = new InicioView();
        inicioView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnFinancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinancasMouseClicked

    private void txtDispesasFuncionariosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDispesasFuncionariosCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasFuncionariosCaretUpdate

    private void txtDispesasFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDispesasFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasFuncionariosActionPerformed

    private void txtDispesasProdutosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDispesasProdutosCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasProdutosCaretUpdate

    private void txtDispesasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDispesasProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasProdutosActionPerformed

    private void txtDispesasFixasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDispesasFixasCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasFixasCaretUpdate

    private void txtDispesasFixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDispesasFixasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispesasFixasActionPerformed

    private void txtTituloCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTituloCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloCaretUpdate

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtPrecoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPrecoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCaretUpdate

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinancasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel btn6;
    private javax.swing.JPanel btnAgenda;
    private javax.swing.JPanel btnAgendamento;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEstoque;
    private javax.swing.JPanel btnFinancas;
    private javax.swing.JPanel btnFuncionarios;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoPrincipalPequena;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel painel;
    private javax.swing.JTable tblFinancas;
    private javax.swing.JLabel traco;
    private javax.swing.JTextField txtDispesasFixas;
    private javax.swing.JTextField txtDispesasFuncionarios;
    private javax.swing.JTextField txtDispesasProdutos;
    private javax.swing.JTextField txtLucroBruto;
    private javax.swing.JTextField txtLucroLiquido;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTotalDispesas;
    private javax.swing.JLabel txtUserLogado;
    // End of variables declaration//GEN-END:variables

    private void calcularTudo() {
        DecimalFormat format = new DecimalFormat("R$ #,##0.00");
        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();

        double lucroBruto = agendamentoDAO.somarLucroBruto();
        txtLucroBruto.setText(format.format(lucroBruto));

        List<Agendamento> agendamentosPagos = agendamentoDAO.getServicosPagos();
        txtDispesasProdutos.setText(format.format(calcularGastoprodutos(agendamentosPagos)));
                
    }

    private void RetornaLinhaTabela() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void remover() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void editar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void preencheTabela() {
        DispesaDAO dispesaDAO = new DispesaDAO();
        String pesquisa = txtPesquisar.getText().toUpperCase();

        List<Dispesa> listaDispesas = dispesaDAO.getDispesas(pesquisa);

        DefaultTableModel tabelaFinancas = (DefaultTableModel) tblFinancas.getModel();
        tabelaFinancas.setRowCount(0);

        for (Dispesa d : listaDispesas) {

            DecimalFormat formato = new DecimalFormat("R$ #,##0.00");
            String precoFormatado = (formato.format(d.getPreco()));

            Object[] obj = new Object[]{
                d.getId(),
                d.getTitulo(),
                precoFormatado
            };
            tabelaFinancas.addRow(obj);
        }

        txtUserLogado.setText(funcionarioLogado.getNome());
    }

    private double calcularGastoprodutos(List<Agendamento> agendamentos) {
        double soma = 0.0;

        for (Agendamento a : agendamentos) {

            EstoqueView estoqueView = new EstoqueView();
            if (a.getServicosSelecionados().isLavagem()) {
                soma += estoqueView.somarDispesa("SHAMPOO");
                soma += estoqueView.somarDispesa("LIMPA-BAU");
                soma += estoqueView.somarDispesa("DESENGRAXANTE");
                soma += estoqueView.somarDispesa("PRETINHO");
            }

            if (a.getServicosSelecionados().isCera()) {
                soma += estoqueView.somarDispesa("CERA");
            }

            if (a.getServicosSelecionados().isPolimento()) {
                soma += estoqueView.somarDispesa("MASSSA-DE-POLIR");
                soma += estoqueView.somarDispesa("CERA");
            }

            if (a.getServicosSelecionados().isRestauracaoPlasticos()) {
                soma += estoqueView.somarDispesa("REVITALIZADOR-DE-PLASTICOS");
            }

            if (a.getServicosSelecionados().isRestauracaoFarois()) {
                soma += estoqueView.somarDispesa("MASSA-DE-POLIR-FAROIS");
            }

            if (a.getServicosSelecionados().isLavagemBancos()) {
                soma += estoqueView.somarDispesa("SHAMPOO");
            }

            if (a.getServicosSelecionados().isAromatizante()) {
                soma += estoqueView.somarDispesa("AROMATIZANTE");
            }
        }
        return soma;
    }
}
