/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendamentoDAO;
import dao.FuncionarioDAO;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;

/**
 *
 * @author pedro
 */
public class FuncionarioView extends javax.swing.JFrame {

    Funcionario funcionarioLogado = LoginView.funcionarioLogado;

    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {
        initComponents();
        preencheTabelaFuncionarios(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuBar = new javax.swing.JPanel();
        logoPrincipalPequena = new javax.swing.JLabel();
        traco = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFinancas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btnEstoque = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        txtPesquisarFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnAgendamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtUserLogado = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtConfirmacao = new javax.swing.JLabel();
        btnDetalhes = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtComissoes = new javax.swing.JTextField();
        btnEditar = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        txtDataInicial = new javax.swing.JFormattedTextField();
        btnFiltrar = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1375, 700));

        menuBar.setBackground(new java.awt.Color(0, 102, 102));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(250, 600));
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarMouseClicked(evt);
            }
        });

        logoPrincipalPequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequena.png"))); // NOI18N

        traco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/traco.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setAutoscrolls(true);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setPreferredSize(new java.awt.Dimension(250, 70));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnInicio.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 103);
        btnInicio.add(jLabel8, gridBagConstraints);

        btnAgenda.setBackground(new java.awt.Color(0, 102, 102));
        btnAgenda.setAutoscrolls(true);
        btnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda.setPreferredSize(new java.awt.Dimension(250, 70));
        btnAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendaMouseExited(evt);
            }
        });
        btnAgenda.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnAgenda.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 83);
        btnAgenda.add(jLabel10, gridBagConstraints);

        btnClientes.setBackground(new java.awt.Color(0, 102, 102));
        btnClientes.setAutoscrolls(true);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setPreferredSize(new java.awt.Dimension(250, 70));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.setLayout(new java.awt.GridBagLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 11, 0);
        btnClientes.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 84);
        btnClientes.add(jLabel12, gridBagConstraints);

        btnFinancas.setBackground(new java.awt.Color(0, 102, 102));
        btnFinancas.setAutoscrolls(true);
        btnFinancas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinancas.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFinancas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinancasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinancasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinancasMouseExited(evt);
            }
        });
        btnFinancas.setLayout(new java.awt.GridBagLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 54, 11, 0);
        btnFinancas.add(jLabel15, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("Finanças");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 78);
        btnFinancas.add(btn6, gridBagConstraints);

        btnEstoque.setBackground(new java.awt.Color(0, 102, 102));
        btnEstoque.setAutoscrolls(true);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setPreferredSize(new java.awt.Dimension(250, 70));
        btnEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseExited(evt);
            }
        });
        btnEstoque.setLayout(new java.awt.GridBagLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnEstoque.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 81);
        btnEstoque.add(jLabel14, gridBagConstraints);

        btnFuncionarios.setBackground(new java.awt.Color(37, 142, 142));
        btnFuncionarios.setAutoscrolls(true);
        btnFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(250, 70));
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });
        btnFuncionarios.setLayout(new java.awt.GridBagLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnFuncionarios.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Funcionários");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 45);
        btnFuncionarios.add(jLabel17, gridBagConstraints);

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setAutoscrolls(true);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setPreferredSize(new java.awt.Dimension(250, 70));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new java.awt.GridBagLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 11, 0);
        btnLogout.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 88);
        btnLogout.add(jLabel19, gridBagConstraints);

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traco)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoPrincipalPequena))))
            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(traco, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoPrincipalPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painel.setBackground(new java.awt.Color(204, 204, 204));
        painel.setPreferredSize(new java.awt.Dimension(820, 600));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        tblFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Telefone", "Salário", "Comissões"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.setPreferredSize(new java.awt.Dimension(730, 400));
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);
        if (tblFuncionarios.getColumnModel().getColumnCount() > 0) {
            tblFuncionarios.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        painel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 1110, 450));

        txtPesquisarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisarFuncionario.setBorder(null);
        txtPesquisarFuncionario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarFuncionarioCaretUpdate(evt);
            }
        });
        txtPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFuncionarioActionPerformed(evt);
            }
        });
        painel.add(txtPesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 290, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pesquisar");
        painel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userLogado.png"))); // NOI18N
        painel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(200, 59, 34));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remover.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Remover");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap())
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        painel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 100, 30));

        btnAgendamento.setBackground(new java.awt.Color(0, 102, 102));
        btnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgendamentoMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastrar");

        javax.swing.GroupLayout btnAgendamentoLayout = new javax.swing.GroupLayout(btnAgendamento);
        btnAgendamento.setLayout(btnAgendamentoLayout);
        btnAgendamentoLayout.setHorizontalGroup(
            btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgendamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        btnAgendamentoLayout.setVerticalGroup(
            btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgendamentoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painel.add(btnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Número");
        painel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtBairro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 260, 30));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNome.setPreferredSize(new java.awt.Dimension(400, 30));
        painel.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Nome");
        painel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Telefone");
        painel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtTelefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" (##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setToolTipText("");
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefone.setPreferredSize(new java.awt.Dimension(400, 30));
        txtTelefone.setRequestFocusEnabled(false);
        painel.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtUserLogado.setBackground(new java.awt.Color(204, 204, 204));
        txtUserLogado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtUserLogado.setForeground(new java.awt.Color(102, 102, 102));
        txtUserLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUserLogado.setToolTipText("");
        painel.add(txtUserLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 269, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Bairro");
        painel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Rua");
        painel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtRua.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtRua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, 30));

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 30));

        txtConfirmacao.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmacao.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtConfirmacao.setForeground(new java.awt.Color(26, 113, 228));
        txtConfirmacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtConfirmacao.setToolTipText("");
        painel.add(txtConfirmacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 269, 20));

        btnDetalhes.setBackground(new java.awt.Color(26, 113, 228));
        btnDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetalhes.setPreferredSize(new java.awt.Dimension(114, 35));
        btnDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetalhesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalhesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalhesMouseExited(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Detalhes");

        javax.swing.GroupLayout btnDetalhesLayout = new javax.swing.GroupLayout(btnDetalhes);
        btnDetalhes.setLayout(btnDetalhesLayout);
        btnDetalhesLayout.setHorizontalGroup(
            btnDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDetalhesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel29)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        btnDetalhesLayout.setVerticalGroup(
            btnDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDetalhesLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        painel.add(btnDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 270, 30));

        txtCep.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 130, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("CEP");
        painel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("CPF");
        painel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtSalario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSalario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSalario.setPreferredSize(new java.awt.Dimension(400, 30));
        painel.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 270, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Comissões");
        painel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        txtComissoes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtComissoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtComissoes.setPreferredSize(new java.awt.Dimension(400, 30));
        painel.add(txtComissoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 270, 30));

        btnEditar.setBackground(new java.awt.Color(26, 113, 228));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Salvar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel35))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        painel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 100, 30));

        txtCpf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setPreferredSize(new java.awt.Dimension(400, 30));
        painel.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Salário");
        painel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotal.setPreferredSize(new java.awt.Dimension(400, 30));
        painel.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 270, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Total");
        painel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Data Final");
        painel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Filtro Comissões");
        painel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("Data Inicial");
        painel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinal.setText("");
        txtDataFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDataFinal.setPreferredSize(new java.awt.Dimension(270, 30));
        painel.add(txtDataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 270, -1));

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.setText("");
        txtDataInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDataInicial.setPreferredSize(new java.awt.Dimension(270, 30));
        painel.add(txtDataInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 270, -1));

        btnFiltrar.setBackground(new java.awt.Color(26, 113, 228));
        btnFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltrar.setPreferredSize(new java.awt.Dimension(114, 35));
        btnFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseExited(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Filtrar");

        javax.swing.GroupLayout btnFiltrarLayout = new javax.swing.GroupLayout(btnFiltrar);
        btnFiltrar.setLayout(btnFiltrarLayout);
        btnFiltrarLayout.setHorizontalGroup(
            btnFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFiltrarLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        btnFiltrarLayout.setVerticalGroup(
            btnFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFiltrarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        painel.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 184, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        btnInicio.setBackground(new Color(37, 142, 142));

        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        btnInicio.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseEntered
        // TODO add your handling code here:
        btnAgenda.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendaMouseEntered

    private void btnAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseExited
        // TODO add your handling code here:
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnAgendaMouseExited

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        ClientesView clientesView = new ClientesView();
        clientesView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnFinancasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseEntered
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFinancasMouseEntered

    private void btnFinancasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseExited
        // TODO add your handling code here:
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFinancasMouseExited

    private void btnEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseClicked
        // TODO add your handling code here:
        EstoqueView estoqueView = new EstoqueView();
        estoqueView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEstoqueMouseClicked

    private void btnEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseEntered
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(37, 142, 142));

        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnEstoqueMouseEntered

    private void btnEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseExited
        // TODO add your handling code here:
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnEstoqueMouseExited

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(37, 142, 142));

        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
        btnLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        // TODO add your handling code here:
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        dispose();
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(37, 142, 142));

        btnFuncionarios.setBackground(new Color(0, 102, 102));
        btnFinancas.setBackground(new Color(0, 102, 102));
        btnInicio.setBackground(new Color(0, 102, 102));
        btnAgenda.setBackground(new Color(0, 102, 102));
        btnClientes.setBackground(new Color(0, 102, 102));
        btnEstoque.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(0, 102, 102));
        btnFuncionarios.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void menuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarMouseClicked

    private void btnDetalhesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalhesMouseExited
        // TODO add your handling code here:
        btnDetalhes.setBackground(new Color(26, 113, 228));
    }//GEN-LAST:event_btnDetalhesMouseExited

    private void btnDetalhesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalhesMouseEntered
        // TODO add your handling code here:
        btnDetalhes.setBackground(new Color(26, 0, 240));
    }//GEN-LAST:event_btnDetalhesMouseEntered

    private void btnDetalhesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalhesMouseClicked
        // TODO add your handling code here:
        detalhesFuncionario();
    }//GEN-LAST:event_btnDetalhesMouseClicked

    private void btnAgendamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseExited
        // TODO add your handling code here:
        btnAgendamento.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnAgendamentoMouseExited

    private void btnAgendamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseEntered
        // TODO add your handling code here:
        btnAgendamento.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnAgendamentoMouseEntered

    private void btnAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendamentoMouseClicked
        // TODO add your handling code here:
        CadastroFuncionarioView cadastroFuncionarioView = new CadastroFuncionarioView();
        cadastroFuncionarioView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgendamentoMouseClicked

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(200, 59, 34));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(160, 0, 0));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFuncionarioActionPerformed

    private void txtPesquisarFuncionarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarFuncionarioCaretUpdate
        // TODO add your handling code here:
        preencheTabelaFuncionarios(false);
    }//GEN-LAST:event_txtPesquisarFuncionarioCaretUpdate

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
        // TODO add your handling code here:
        RetornaLinhaTabela();
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        preencheTabelaFuncionarios(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void btnAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendaMouseClicked
        // TODO add your handling code here:
        AgendaView agendaView = new AgendaView();
        agendaView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgendaMouseClicked

    private void btnFinancasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancasMouseClicked
        // TODO add your handling code here:
        FinancasView financasView = new FinancasView();
        financasView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFinancasMouseClicked

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        InicioView inicioView = new InicioView();
        inicioView.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseClicked
        // TODO add your handling code here:
        preencheTabelaFuncionarios(true);
    }//GEN-LAST:event_btnFiltrarMouseClicked

    private void btnFiltrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarMouseEntered

    private void btnFiltrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn6;
    private javax.swing.JPanel btnAgenda;
    private javax.swing.JPanel btnAgendamento;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnDetalhes;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEstoque;
    private javax.swing.JPanel btnFiltrar;
    private javax.swing.JPanel btnFinancas;
    private javax.swing.JPanel btnFuncionarios;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoPrincipalPequena;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel painel;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JLabel traco;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtComissoes;
    private javax.swing.JLabel txtConfirmacao;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisarFuncionario;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtUserLogado;
    // End of variables declaration//GEN-END:variables

    public void preencheTabelaFuncionarios(boolean comFiltro) {
        String dataInicialString = "";
        String dataFinalString = "";

        if (comFiltro) {
            if (validarFormatoData(txtDataInicial.getText())) {
                dataInicialString = txtDataInicial.getText();
            } else {
                txtConfirmacao.setText("Data inválida");
                return;
            }
            if (validarFormatoData(txtDataFinal.getText())) {
                dataFinalString = txtDataFinal.getText();
            } else {
                txtConfirmacao.setText("Data inválida");
                return;
            }
        }

        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        String pesquisa = txtPesquisarFuncionario.getText().toUpperCase();

        List<Funcionario> listaFuncionarios = funcionarioDAO.getFuncionarios(pesquisa);

        DefaultTableModel tabelaFuncionarios = (DefaultTableModel) tblFuncionarios.getModel();
        tabelaFuncionarios.setRowCount(0);

        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();

        for (Funcionario a : listaFuncionarios) {
            double comissao = 0.0;
            if (comFiltro) {
                DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate dataInicial = LocalDate.parse(dataInicialString, formatoData);
                LocalDate dataFinal = LocalDate.parse(dataFinalString, formatoData);
                comissao = agendamentoDAO.calcularComissaoFuncionario(a.getId(), dataInicial, dataFinal);
            } else {
                comissao = agendamentoDAO.calcularComissaoFuncionario(a.getId());
            }
            DecimalFormat format = new DecimalFormat("R$ #,##0.00");
            Object[] obj = new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),
                format.format(a.getSalario()),
                format.format(comissao)
            };
            tabelaFuncionarios.addRow(obj);
        }

        txtUserLogado.setText(funcionarioLogado.getNome());
    }

    public void RetornaLinhaTabela() {
        limparCampos();
        DecimalFormat format = new DecimalFormat("R$ #,##0.00");
        DefaultTableModel tblModel = (DefaultTableModel) tblFuncionarios.getModel();
        int i = tblFuncionarios.getSelectedRow();
        String id = tblModel.getValueAt(i, 0).toString();

        int idPesquisa = Integer.parseInt(id);
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        Funcionario funcionario = funcionarioDAO.getFuncionario(idPesquisa);

        txtNome.setText(funcionario.getNome());
        txtTelefone.setText(funcionario.getTelefone());
        txtCpf.setText(funcionario.getCpf());
        txtCep.setText(funcionario.getCep());
        txtBairro.setText(funcionario.getBairro());
        txtRua.setText(funcionario.getRua());
        txtNumero.setText(funcionario.getNumero());
        txtSalario.setText(format.format(funcionario.getSalario()));
        txtConfirmacao.setText("");

        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
        
        double comissao = 0.0;
        if (validarFormatoData(txtDataInicial.getText()) && validarFormatoData(txtDataFinal.getText())) {
            String dataInicialString = txtDataInicial.getText();
            String dataFinalString = txtDataFinal.getText();
            DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataInicial = LocalDate.parse(dataInicialString, formatoData);
            LocalDate dataFinal = LocalDate.parse(dataFinalString, formatoData);
            comissao = agendamentoDAO.calcularComissaoFuncionario(idPesquisa, dataInicial, dataFinal);
        }else{
            comissao = agendamentoDAO.calcularComissaoFuncionario(idPesquisa);
        }
        txtComissoes.setText(format.format(comissao));
        txtTotal.setText(format.format(funcionario.getSalario() + comissao));
    }

    public void remover() {
        int op = JOptionPane.showConfirmDialog(null, "Deseja cancelar o funcionario selecionado?");
        if (op == 0) {
            DefaultTableModel tblModel = (DefaultTableModel) tblFuncionarios.getModel();
            int i = tblFuncionarios.getSelectedRow();
            String id = tblModel.getValueAt(i, 0).toString();

            int idPesquisa = Integer.parseInt(id);
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            funcionarioDAO.remover(idPesquisa);

            txtConfirmacao.setText("funcionario cancelado com sucesso.");
            preencheTabelaFuncionarios(false);
        }
        limparCampos();
    }

    private void limparCampos() {
        txtNome.setText("");
        txtTelefone.setText("");
        txtCpf.setText("");
        txtCep.setText("");
        txtBairro.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtComissoes.setText("");
        txtSalario.setText("");
        txtConfirmacao.setText("");
    }

    private void editar() {
        DefaultTableModel tblModel = (DefaultTableModel) tblFuncionarios.getModel();
        int i = tblFuncionarios.getSelectedRow();
        String idString = tblModel.getValueAt(i, 0).toString();

        if (!idString.equals("")) {
            int id = Integer.parseInt(idString);

            int op = JOptionPane.showConfirmDialog(null, ("Deseja editar o funcionario selecionado de id = " + id + " ?"));

            if (op == 0) {
                String nome = txtNome.getText().toUpperCase();
                String telefone = txtTelefone.getText();
                String bairro = txtBairro.getText();
                String rua = txtRua.getText();
                String numero = txtNumero.getText();
                String cpf = txtCpf.getText();
                String cep = txtCep.getText();
                
                String salarioFormatado = txtSalario.getText().trim();
                if (salarioFormatado.substring(0, 2).equals("R$")) {
                    salarioFormatado = salarioFormatado.substring(2);
                }
                double salario = convertarPrecoFormatadoParaDouble(salarioFormatado);
                
                String comissoesFormatado = txtComissoes.getText().trim();
                if (comissoesFormatado.substring(0, 2).equals("R$")) {
                    comissoesFormatado = comissoesFormatado.substring(2);
                }
                double comissoes = convertarPrecoFormatadoParaDouble(comissoesFormatado);

                Funcionario funcionario = new Funcionario();
                funcionario.setId(id);
                funcionario.setNome(nome);
                funcionario.setTelefone(telefone);
                funcionario.setCpf(cpf);
                funcionario.setCep(cep);
                funcionario.setBairro(bairro);
                funcionario.setRua(rua);
                funcionario.setNumero(numero);
                funcionario.setSalario(salario);
                funcionario.setComissoes(comissoes);
                //funcionario.setAcesso(acesso);

                FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
                funcionarioDAO.editar(funcionario);

                System.out.println("funcionario editado com sucesso.");
                preencheTabelaFuncionarios(false);
                limparCampos();
            }
        }

    }

    private void detalhesFuncionario() {
        DefaultTableModel tblModel = (DefaultTableModel) tblFuncionarios.getModel();
        int i = tblFuncionarios.getSelectedRow();
        String idString = tblModel.getValueAt(i, 0).toString();

        if (!idString.equals("")) {
            int id = Integer.parseInt(idString);
            System.out.println(id);
            DetalhesCliente detalhesCliente = new DetalhesCliente(id);
            detalhesCliente.setVisible(true);
        } else {
            txtConfirmacao.setText("Selecione um funcionário na tabela!");
        }

    }

    public boolean validarFormatoData(String dataString) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // Desativa a tolerância de datas inválidas

        try {
            sdf.parse(dataString);
            return true; // A data é válida no formato especificado
        } catch (ParseException e) {
            return false; // A data é inválida no formato especificado
        }
    }
    
    public double convertarPrecoFormatadoParaDouble(String valorFormatado) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
        char decimalSeparator = symbols.getDecimalSeparator();

        // Removendo o separador de milhar, caso exista
        valorFormatado = valorFormatado.replace(Character.toString(symbols.getGroupingSeparator()), "");

        // Substituindo a vírgula pelo ponto
        valorFormatado = valorFormatado.replace(Character.toString(decimalSeparator), ".");

        double valorDouble = Double.parseDouble(valorFormatado);
        return valorDouble;
    }
}
