/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.text.DecimalFormat;
import model.Agendamento;
import model.Funcionario;
import model.Selecionados;

/**
 *
 * @author Pedro
 */
public class NovoAgendamentoServicosView extends javax.swing.JFrame {
    
    double soma;
    Funcionario funcionarioLogado = LoginView.funcionarioLogado;
    private Agendamento agendamento;
    /**
     * Creates new form NovoAgendamentoView
     * @param agendamento
     */
   
    public NovoAgendamentoServicosView(Agendamento agendamento) {
        initComponents();
        this.agendamento = agendamento;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProximoServicos = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtbAromatizante = new javax.swing.JToggleButton();
        jtbLavagemBancos = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtbRestauracaoFarois = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jtbRestauracaoPlasticos = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jtbPolimento = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jtbCera = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jtbLavagem = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProximoServicos.setBackground(new java.awt.Color(0, 102, 102));
        btnProximoServicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximoServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProximoServicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProximoServicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProximoServicosMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/next.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("PROXIMO");

        javax.swing.GroupLayout btnProximoServicosLayout = new javax.swing.GroupLayout(btnProximoServicos);
        btnProximoServicos.setLayout(btnProximoServicosLayout);
        btnProximoServicosLayout.setHorizontalGroup(
            btnProximoServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProximoServicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        btnProximoServicosLayout.setVerticalGroup(
            btnProximoServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProximoServicosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnProximoServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(btnProximoServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 770, 127, 35));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("R$ 10,00");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 760, -1, -1));

        jtbAromatizante.setBackground(new java.awt.Color(0, 102, 102));
        jtbAromatizante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbAromatizante.setForeground(new java.awt.Color(255, 255, 255));
        jtbAromatizante.setText("Aromatizante");
        jtbAromatizante.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbAromatizante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbAromatizanteActionPerformed(evt);
            }
        });
        jPanel1.add(jtbAromatizante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, -1, -1));

        jtbLavagemBancos.setBackground(new java.awt.Color(0, 102, 102));
        jtbLavagemBancos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbLavagemBancos.setForeground(new java.awt.Color(255, 255, 255));
        jtbLavagemBancos.setText("Lavagem Bancos");
        jtbLavagemBancos.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbLavagemBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbLavagemBancosActionPerformed(evt);
            }
        });
        jPanel1.add(jtbLavagemBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("R$ 50,00");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("R$ 50,00");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, -1, -1));

        jtbRestauracaoFarois.setBackground(new java.awt.Color(0, 102, 102));
        jtbRestauracaoFarois.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbRestauracaoFarois.setForeground(new java.awt.Color(255, 255, 255));
        jtbRestauracaoFarois.setText("Restauração Farois");
        jtbRestauracaoFarois.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbRestauracaoFarois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbRestauracaoFaroisActionPerformed(evt);
            }
        });
        jPanel1.add(jtbRestauracaoFarois, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("R$ 10,00");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        jtbRestauracaoPlasticos.setBackground(new java.awt.Color(0, 102, 102));
        jtbRestauracaoPlasticos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbRestauracaoPlasticos.setForeground(new java.awt.Color(255, 255, 255));
        jtbRestauracaoPlasticos.setText("Restauraçao Plásticos");
        jtbRestauracaoPlasticos.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbRestauracaoPlasticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbRestauracaoPlasticosActionPerformed(evt);
            }
        });
        jPanel1.add(jtbRestauracaoPlasticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("R$ 200,00");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jtbPolimento.setBackground(new java.awt.Color(0, 102, 102));
        jtbPolimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbPolimento.setForeground(new java.awt.Color(255, 255, 255));
        jtbPolimento.setText("Polimento");
        jtbPolimento.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbPolimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbPolimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jtbPolimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("R$ 10,00");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        jtbCera.setBackground(new java.awt.Color(0, 102, 102));
        jtbCera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbCera.setForeground(new java.awt.Color(255, 255, 255));
        jtbCera.setText("Cera");
        jtbCera.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbCera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCeraActionPerformed(evt);
            }
        });
        jPanel1.add(jtbCera, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("R$ 40,00");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jtbLavagem.setBackground(new java.awt.Color(0, 102, 102));
        jtbLavagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbLavagem.setForeground(new java.awt.Color(255, 255, 255));
        jtbLavagem.setText("Lavagem");
        jtbLavagem.setPreferredSize(new java.awt.Dimension(200, 30));
        jtbLavagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLavagemMouseClicked(evt);
            }
        });
        jtbLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbLavagemActionPerformed(evt);
            }
        });
        jPanel1.add(jtbLavagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cera.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lavagem.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/polimento.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plasticos.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lavagemBanco.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/polimentoFarol.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aromatizante.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, -1, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(51, 51, 51));
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 730, 127, 35));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("R$ 10,00");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 760, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequena.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 140));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("TOTAL R$");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 710, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(0, 102, 102));
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerda.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("VOLTAR");

        javax.swing.GroupLayout btnVoltarLayout = new javax.swing.GroupLayout(btnVoltar);
        btnVoltar.setLayout(btnVoltarLayout);
        btnVoltarLayout.setHorizontalGroup(
            btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVoltarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
        );
        btnVoltarLayout.setVerticalGroup(
            btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVoltarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 770, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbLavagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbLavagemActionPerformed

    private void jtbRestauracaoFaroisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbRestauracaoFaroisActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbRestauracaoFaroisActionPerformed

    private void jtbAromatizanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbAromatizanteActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbAromatizanteActionPerformed

    private void jtbLavagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLavagemMouseClicked
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbLavagemMouseClicked

    private void jtbCeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbCeraActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbCeraActionPerformed

    private void jtbPolimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbPolimentoActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbPolimentoActionPerformed

    private void jtbRestauracaoPlasticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbRestauracaoPlasticosActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbRestauracaoPlasticosActionPerformed

    private void jtbLavagemBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbLavagemBancosActionPerformed
        // TODO add your handling code here:
        somaServicos();
    }//GEN-LAST:event_jtbLavagemBancosActionPerformed

    private void btnProximoServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoServicosMouseClicked
        NovoAgendamentoConfirmacaoView novoAgendamentoConfirmacaoView = new NovoAgendamentoConfirmacaoView(this.agendamento);
        dispose();
        novoAgendamentoConfirmacaoView.setVisible(true);
    }//GEN-LAST:event_btnProximoServicosMouseClicked

    private void btnProximoServicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoServicosMouseEntered
        // TODO add your handling code here:
        btnProximoServicos.setBackground(new Color(37,142,142));
    }//GEN-LAST:event_btnProximoServicosMouseEntered

    private void btnProximoServicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoServicosMouseExited
        // TODO add your handling code here:\\
        btnProximoServicos.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnProximoServicosMouseExited

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        // TODO add your handling code here:
        NovoAgendamentoDadosView novoAgendamentoDadosView = new NovoAgendamentoDadosView();
        dispose();
        novoAgendamentoDadosView.setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(new Color(37,142,142));
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_btnVoltarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoAgendamentoServicosView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnProximoServicos;
    private javax.swing.JPanel btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jtbAromatizante;
    private javax.swing.JToggleButton jtbCera;
    private javax.swing.JToggleButton jtbLavagem;
    private javax.swing.JToggleButton jtbLavagemBancos;
    private javax.swing.JToggleButton jtbPolimento;
    private javax.swing.JToggleButton jtbRestauracaoFarois;
    private javax.swing.JToggleButton jtbRestauracaoPlasticos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    /**
     * Faz a soma dos serviços selecionados e seta txtTotal com o valor total,
     * além disso retorna Selecionados que são um conjunto de booleans com os nomes dos serviços,
     * ou sejá, retorna true para os seviços que estão selecionados
     * 
     * 
     * @return
     */
    public void somaServicos() {
        double soma = 0;
        boolean lavagem = false;
        boolean cera = false;
        boolean polimento = false;
        boolean restauracaoPlasticos = false;
        boolean restauracaoFarois = false;
        boolean lavagemBancos = false;
        boolean aromatizante = false;
        
        if(jtbLavagem.isSelected()){
            soma += 40;
            lavagem = true;
            jtbLavagem.setBackground(new Color(200,59,34));
        }else{
            jtbLavagem.setBackground(new Color(0,102,102));
        }
            
        if(jtbCera.isSelected()){
            soma += 10;
            cera = true;
            jtbCera.setBackground(new Color(200,59,34));
        }else{
            jtbCera.setBackground(new Color(0,102,102));            
        }
        
        if(jtbPolimento.isSelected()){
            soma += 200;
            polimento = true;
            jtbPolimento.setBackground(new Color(200,59,34));
        }else{
            jtbPolimento.setBackground(new Color(0,102,102));            
        }
        
        if(jtbRestauracaoPlasticos.isSelected()){
            soma += 10;
            restauracaoPlasticos = true;
            jtbRestauracaoPlasticos.setBackground(new Color(200,59,34));
        }else{
            jtbRestauracaoPlasticos.setBackground(new Color(0,102,102));            
        }
        
        if(jtbRestauracaoFarois.isSelected()){
            soma += 50;
            restauracaoFarois = true;
            jtbRestauracaoFarois.setBackground(new Color(200,59,34));
        }else{
            jtbRestauracaoFarois.setBackground(new Color(0,102,102));            
        }
        
        if(jtbLavagemBancos.isSelected()){
            soma += 50;
            lavagemBancos = true;
            jtbLavagemBancos.setBackground(new Color(200,59,34));
        }else{
            jtbLavagemBancos.setBackground(new Color(0,102,102));            
        }
        
        if(jtbAromatizante.isSelected()){
            soma += 10;
            aromatizante = true;
            jtbAromatizante.setBackground(new Color(200,59,34));
        }else{
            jtbAromatizante.setBackground(new Color(0,102,102));            
        }
        
        DecimalFormat format = new DecimalFormat("R$ #,##0.00");
        String valorFormatado = format.format(soma);       
        txtTotal.setText(valorFormatado);
        
        
        Selecionados itensSelecionados = new Selecionados(lavagem,
            cera,
            polimento,
            restauracaoPlasticos,
            restauracaoFarois,
            lavagemBancos,
            aromatizante);
        
        this.agendamento.setPreco(soma);
        this.agendamento.setServicosSelecionados(itensSelecionados);
    }

}