/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendamentoDAO;
import dao.FuncionarioDAO;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.util.List;
import model.Agendamento;
import model.Funcionario;

/**
 *
 * @author Pedro
 */
public class NovoAgendamentoConfirmacaoView extends javax.swing.JFrame {

    Funcionario funcionarioLogado = LoginView.funcionarioLogado;
    private Agendamento agendamento;
    StringBuilder servicosString = new StringBuilder();

    /**
     * Creates new form NovoAgendamentoConfirmacaoView
     */
    public NovoAgendamentoConfirmacaoView(Agendamento agendamento) {
        this.agendamento = agendamento;
        initComponents();
        preencheLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtVeiculo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jtbLavagem = new javax.swing.JCheckBox();
        jtbCera = new javax.swing.JCheckBox();
        jtbPolimento = new javax.swing.JCheckBox();
        jtbRestauracaoPlasticos = new javax.swing.JCheckBox();
        jtbRestauracaoFarois = new javax.swing.JCheckBox();
        jtbLavagemBancos = new javax.swing.JCheckBox();
        jtbAromatizante = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jcbFuncionarioResponsavel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequena.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(490, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 102));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/next.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CONFIRMAR");

        javax.swing.GroupLayout btnConfirmarLayout = new javax.swing.GroupLayout(btnConfirmar);
        btnConfirmar.setLayout(btnConfirmarLayout);
        btnConfirmarLayout.setHorizontalGroup(
            btnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfirmarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        btnConfirmarLayout.setVerticalGroup(
            btnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfirmarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(0, 102, 102));
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerda.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VOLTAR");

        javax.swing.GroupLayout btnVoltarLayout = new javax.swing.GroupLayout(btnVoltar);
        btnVoltar.setLayout(btnVoltarLayout);
        btnVoltarLayout.setHorizontalGroup(
            btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVoltarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        btnVoltarLayout.setVerticalGroup(
            btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVoltarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(btnVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Veículo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Telefone");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 189, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Endereço");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 246, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Data");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 303, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Hora");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("CONFIRMAÇÃO");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefone.setEnabled(false);
        txtTelefone.setMaximumSize(new java.awt.Dimension(380, 35));
        txtTelefone.setMinimumSize(new java.awt.Dimension(380, 35));
        txtTelefone.setPreferredSize(new java.awt.Dimension(380, 35));
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 206, -1, -1));

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEndereco.setEnabled(false);
        txtEndereco.setMaximumSize(new java.awt.Dimension(380, 35));
        txtEndereco.setMinimumSize(new java.awt.Dimension(380, 35));
        txtEndereco.setPreferredSize(new java.awt.Dimension(380, 35));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 263, -1, -1));

        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHora.setEnabled(false);
        txtHora.setMaximumSize(new java.awt.Dimension(380, 35));
        txtHora.setMinimumSize(new java.awt.Dimension(380, 35));
        txtHora.setPreferredSize(new java.awt.Dimension(380, 35));
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 381, -1, -1));

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setEnabled(false);
        txtData.setMaximumSize(new java.awt.Dimension(380, 35));
        txtData.setMinimumSize(new java.awt.Dimension(380, 35));
        txtData.setPreferredSize(new java.awt.Dimension(380, 35));
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jPanel2.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 319, -1, -1));

        txtVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVeiculo.setEnabled(false);
        txtVeiculo.setMaximumSize(new java.awt.Dimension(380, 35));
        txtVeiculo.setMinimumSize(new java.awt.Dimension(380, 35));
        txtVeiculo.setPreferredSize(new java.awt.Dimension(380, 35));
        txtVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 148, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        txtNome.setMaximumSize(new java.awt.Dimension(380, 35));
        txtNome.setMinimumSize(new java.awt.Dimension(380, 35));
        txtNome.setPreferredSize(new java.awt.Dimension(380, 35));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 86, -1, -1));

        jtbLavagem.setBackground(new java.awt.Color(255, 255, 255));
        jtbLavagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbLavagem.setText("Lavagem");
        jtbLavagem.setEnabled(false);
        jtbLavagem.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbLavagem.setRequestFocusEnabled(false);
        jtbLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbLavagemActionPerformed(evt);
            }
        });
        jPanel2.add(jtbLavagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jtbCera.setBackground(new java.awt.Color(255, 255, 255));
        jtbCera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbCera.setText("Cera");
        jtbCera.setEnabled(false);
        jtbCera.setFocusPainted(false);
        jtbCera.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbCera.setRequestFocusEnabled(false);
        jPanel2.add(jtbCera, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jtbPolimento.setBackground(new java.awt.Color(255, 255, 255));
        jtbPolimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbPolimento.setText("Polimento");
        jtbPolimento.setEnabled(false);
        jtbPolimento.setFocusPainted(false);
        jtbPolimento.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbPolimento.setRequestFocusEnabled(false);
        jPanel2.add(jtbPolimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jtbRestauracaoPlasticos.setBackground(new java.awt.Color(255, 255, 255));
        jtbRestauracaoPlasticos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbRestauracaoPlasticos.setText("Restauração Plásticos");
        jtbRestauracaoPlasticos.setEnabled(false);
        jtbRestauracaoPlasticos.setFocusPainted(false);
        jtbRestauracaoPlasticos.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbRestauracaoPlasticos.setRequestFocusEnabled(false);
        jPanel2.add(jtbRestauracaoPlasticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jtbRestauracaoFarois.setBackground(new java.awt.Color(255, 255, 255));
        jtbRestauracaoFarois.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbRestauracaoFarois.setText("Restauração Faróis");
        jtbRestauracaoFarois.setEnabled(false);
        jtbRestauracaoFarois.setFocusPainted(false);
        jtbRestauracaoFarois.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbRestauracaoFarois.setRequestFocusEnabled(false);
        jPanel2.add(jtbRestauracaoFarois, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jtbLavagemBancos.setBackground(new java.awt.Color(255, 255, 255));
        jtbLavagemBancos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbLavagemBancos.setText("Lavagem Bancos");
        jtbLavagemBancos.setEnabled(false);
        jtbLavagemBancos.setFocusPainted(false);
        jtbLavagemBancos.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbLavagemBancos.setRequestFocusEnabled(false);
        jPanel2.add(jtbLavagemBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jtbAromatizante.setBackground(new java.awt.Color(255, 255, 255));
        jtbAromatizante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbAromatizante.setText("Aromatizante");
        jtbAromatizante.setEnabled(false);
        jtbAromatizante.setFocusPainted(false);
        jtbAromatizante.setPreferredSize(new java.awt.Dimension(160, 35));
        jtbAromatizante.setRequestFocusEnabled(false);
        jtbAromatizante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbAromatizanteActionPerformed(evt);
            }
        });
        jPanel2.add(jtbAromatizante, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Funcionário Responsável");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jcbFuncionarioResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbFuncionarioResponsavel.setPreferredSize(new java.awt.Dimension(380, 35));
        jcbFuncionarioResponsavel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFuncionarioResponsavelItemStateChanged(evt);
            }
        });
        jcbFuncionarioResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFuncionarioResponsavelActionPerformed(evt);
            }
        });
        jPanel2.add(jcbFuncionarioResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        // TODO add your handling code here:
        confirmarAgendamento();
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        // TODO add your handling code here:
        btnConfirmar.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        // TODO add your handling code here:
        btnConfirmar.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnConfirmarMouseExited

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        // TODO add your handling code here:
        NovoAgendamentoServicosView novoAgendamentoServicosView = new NovoAgendamentoServicosView(this.agendamento);
        dispose();
        novoAgendamentoServicosView.setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        // TODO add your handling code here:
        btnVoltar.setBackground(new Color(37, 142, 142));
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        // TODO add your handling code here:
        btnVoltar.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnVoltarMouseExited

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeiculoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtVeiculoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jtbLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbLavagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbLavagemActionPerformed

    private void jtbAromatizanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbAromatizanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbAromatizanteActionPerformed

    private void jcbFuncionarioResponsavelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFuncionarioResponsavelItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFuncionarioResponsavelItemStateChanged

    private void jcbFuncionarioResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFuncionarioResponsavelActionPerformed
        atribuirServicoAoFuncionario();
    }//GEN-LAST:event_jcbFuncionarioResponsavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoConfirmacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoConfirmacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoConfirmacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoAgendamentoConfirmacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoAgendamentoConfirmacaoView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnConfirmar;
    private javax.swing.JPanel btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbFuncionarioResponsavel;
    private javax.swing.JCheckBox jtbAromatizante;
    private javax.swing.JCheckBox jtbCera;
    private javax.swing.JCheckBox jtbLavagem;
    private javax.swing.JCheckBox jtbLavagemBancos;
    private javax.swing.JCheckBox jtbPolimento;
    private javax.swing.JCheckBox jtbRestauracaoFarois;
    private javax.swing.JCheckBox jtbRestauracaoPlasticos;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtVeiculo;
    // End of variables declaration//GEN-END:variables

    private void preencheLabel() {
        txtNome.setText(this.agendamento.getCliente());
        txtVeiculo.setText(this.agendamento.getVeiculo());
        txtTelefone.setText(this.agendamento.getContato());
        DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataString = this.agendamento.getData().format(formatoData);
        txtData.setText(dataString);
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
        String horarioString = this.agendamento.getHora().format(formatoHora);
        txtHora.setText(horarioString);

        StringBuilder enderecoSB = new StringBuilder();

        if (!agendamento.getRua().equals("")) {
            enderecoSB.append("Rua " + agendamento.getRua());
        }
        if (!agendamento.getNumero().equals("")) {
            enderecoSB.append(", Número " + agendamento.getNumero());
        }
        if (!agendamento.getBairro().equals("")) {
            enderecoSB.append(", Bairro " + agendamento.getBairro());
        }

        String endereco = enderecoSB.toString();
        txtEndereco.setText(endereco);

        this.agendamento.setPagamento(false);

        selecionarFuncionarioResponsavel();
        
    }

    private void selecionarFuncionarioResponsavel() {
        if (this.funcionarioLogado.isAcesso()) {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            List<Funcionario> funcionarios = funcionarioDAO.getFuncionarios("");

            for (Funcionario f : funcionarios) {
                jcbFuncionarioResponsavel.addItem(f.getNome());
            }
        } else {
            jcbFuncionarioResponsavel.addItem(this.funcionarioLogado.getNome());
        }
    }
    
    private void atribuirServicoAoFuncionario() {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            List<Funcionario> funcionarios = funcionarioDAO.getFuncionarios(jcbFuncionarioResponsavel.getSelectedItem().toString());

            for (Funcionario f : funcionarios) {
                 this.agendamento.setIdFuncionarioResponsavel(f.getId());
            }
        
    }
    
    private void confirmarAgendamento(){
        EstoqueView estoqueView = new EstoqueView();
        if (agendamento.getServicosSelecionados().isLavagem()){ 
            jtbLavagem.setSelected(true);
            estoqueView.subtrairProduto("SHAMPOO");
            estoqueView.subtrairProduto("LIMPA-BAU");
            estoqueView.subtrairProduto("DESENGRAXANTE");
            estoqueView.subtrairProduto("PRETINHO");
        }    

        if (agendamento.getServicosSelecionados().isCera()){
            jtbCera.setSelected(true);
            estoqueView.subtrairProduto("CERA");
        } 

        if (agendamento.getServicosSelecionados().isPolimento()){
            jtbPolimento.setSelected(true);
            estoqueView.subtrairProduto("MASSSA-DE-POLIR");            
            estoqueView.subtrairProduto("CERA");            
        } 

        if (agendamento.getServicosSelecionados().isRestauracaoPlasticos()) {
            jtbRestauracaoPlasticos.setSelected(true);
            estoqueView.subtrairProduto("REVITALIZADOR-DE-PLASTICOS");
        }

        if (agendamento.getServicosSelecionados().isRestauracaoFarois()) {
            jtbRestauracaoFarois.setSelected(true);      
            estoqueView.subtrairProduto("MASSA-DE-POLIR-FAROIS");
        }

        if (agendamento.getServicosSelecionados().isLavagemBancos()){
            jtbLavagemBancos.setSelected(true);
            estoqueView.subtrairProduto("SHAMPOO");
        }
       
        if (agendamento.getServicosSelecionados().isAromatizante()) {
            jtbAromatizante.setSelected(true);
            estoqueView.subtrairProduto("AROMATIZANTE");
        }
        AgendamentoDAO agendamentoDAO = new AgendamentoDAO();
        agendamentoDAO.inserir(agendamento);
        AgendaView agendaView = new AgendaView();
        agendaView.dispose();
        agendaView.setVisible(true);
        dispose();
    }

}
